import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import DarkModeToggle from "@/components/DarkModeToggle";
import ThemeProvider from "@/components/ThemeProvider";
import Stepper from "@/components/Stepper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "kidev",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <div className="relative max-w-[2560px] mx-auto
          p-8 md:pt-24 lg:pt-32 2xl:pt-64 md:px-24 lg:px-32 2xl:px-64 h-dvh overflow-y-auto">
            <Navigation />

            {/* Wrapper for contents */}
            {children}

            <Stepper />
            <DarkModeToggle />

          </div>

        </ThemeProvider>

      </body>
    </html>
  );
}
